name: Java CI with Gradle # A CI pipeline to do automated testing

# Trigger the workflow on every push or pull request to the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build: # The name of the job
    runs-on: ubuntu-latest

    steps:
      # Checkout the current repository code
      - uses: actions/checkout@v3

      # Set up JDK 17 for CS2103T
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # What is this?

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Run the Gradle build, Compile the code and runs JUnit tests and ensures Checkstyle adhered to
      - name: Build with Gradle
        run: ./gradlew build







